name: Build Tesseract Portable EXE on Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    # Step 1: Install vcpkg and dependencies like Leptonica
    - name: Install vcpkg and dependencies
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg.exe integrate install
        .\vcpkg\vcpkg.exe install tesseract:x64-windows-static

    # Step 2: Configure CMake for Tesseract
    - name: Configure CMake
      run: cmake -B build -A x64 -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DBUILD_SHARED_LIBS=OFF

    # Step 3: Build Tesseract
    - name: Build Tesseract
      run: cmake --build build --config ${{ env.BUILD_TYPE }}

    # Step 4: Package the portable EXE with its dependencies
    - name: Package portable EXE
      run: |
        mkdir output
        # Copy the executable and all necessary DLLs to output folder
        copy build\Release\tesseract.exe output\
        for /R %i in (*.dll) do copy "%i" output\

    # Step 5: Upload the executable as an artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: tesseract-portable-exe
        path: output
